# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.Person'),
        ),
    ]
