# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171003_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Person'),
        ),
    ]
